module.exports = {
  mode: 'jit',
  experimental: {
    optimizeUniversalDefaults: true,
  },
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      gap: {
        16: 'var(--space-16)',
      },
    },
    screens: {
      sm: { max: '991px' },
      md: { min: '991px', max: '1199px' },
      lg: { min: '1199px', max: '1400px' },
      xl: { min: '1400px', max: '1600px' },
      xxl: { min: '1600px' },
    },
  },
  corePlugins: {
    // *  Disable all core plugins by default only enabled grid * //
    preflight: false,
    container: false,
    space: false,
    divideWidth: false,
    divideColor: false,
    divideStyle: false,
    divideOpacity: false,
    accessibility: false,
    appearance: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundColor: false,
    backgroundImage: false,
    gradientColorStops: false,
    backgroundOpacity: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderColor: false,
    borderOpacity: false,
    borderRadius: false,
    borderStyle: false,
    borderWidth: false,
    boxSizing: false,
    cursor: false,
    display: true,
    flexDirection: false,
    flexWrap: false,
    placeItems: false,
    placeContent: false,
    placeSelf: false,
    alignItems: false,
    alignContent: false,
    alignSelf: false,
    justifyItems: false,
    justifyContent: false,
    justifySelf: false,
    flex: false,
    flexGrow: false,
    filter: false,
    flexShrink: false,
    order: false,
    float: false,
    clear: false,
    fontFamily: false,
    fontWeight: false,
    height: false,
    lineHeight: false,
    listStylePosition: false,
    listStyleType: false,
    margin: false,
    maxHeight: false,
    maxWidth: false,
    minHeight: false,
    minWidth: false,
    objectFit: false,
    objectPosition: false,
    opacity: false,
    outline: false,
    overflow: false,
    overscrollBehavior: false,
    padding: false,
    placeholderColor: false,
    placeholderOpacity: false,
    pointerEvents: false,
    position: false,
    inset: false,
    resize: false,
    boxShadow: false,
    ringWidth: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringColor: false,
    ringOpacity: false,
    fill: false,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    textAlign: false,
    textColor: false,
    textOpacity: false,
    textOverflow: false,
    fontStyle: false,
    textTransform: false,
    textDecoration: false,
    fontSmoothing: false,
    fontVariantNumeric: false,
    letterSpacing: false,
    userSelect: false,
    verticalAlign: false,
    visibility: false,
    whitespace: false,
    wordBreak: false,
    width: false,
    zIndex: false,
    gap: true,
    gridAutoFlow: true,
    gridTemplateColumns: true,
    gridAutoColumns: true,
    gridColumn: true,
    gridColumnStart: true,
    gridColumnEnd: true,
    gridTemplateRows: true,
    gridAutoRows: true,
    gridRow: true,
    gridRowStart: true,
    gridRowEnd: true,
    transform: false,
    transformOrigin: false,
    scale: false,
    rotate: false,
    translate: false,
    skew: false,
    transitionProperty: false,
    transitionTimingFunction: false,
    transitionDuration: false,
    transitionDelay: false,
    animation: false,
  },
  plugins: [],
};
